//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Router.ProxyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyService.IProxy")]
    public interface IProxy {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/GetAllStation", ReplyAction="http://tempuri.org/IProxy/GetAllStationResponse")]
        string GetAllStation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/GetAllStation", ReplyAction="http://tempuri.org/IProxy/GetAllStationResponse")]
        System.Threading.Tasks.Task<string> GetAllStationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/GetStation", ReplyAction="http://tempuri.org/IProxy/GetStationResponse")]
        string GetStation(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxy/GetStation", ReplyAction="http://tempuri.org/IProxy/GetStationResponse")]
        System.Threading.Tasks.Task<string> GetStationAsync(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyChannel : Router.ProxyService.IProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyClient : System.ServiceModel.ClientBase<Router.ProxyService.IProxy>, Router.ProxyService.IProxy {
        
        public ProxyClient() {
        }
        
        public ProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllStation() {
            return base.Channel.GetAllStation();
        }
        
        public System.Threading.Tasks.Task<string> GetAllStationAsync() {
            return base.Channel.GetAllStationAsync();
        }
        
        public string GetStation(string key) {
            return base.Channel.GetStation(key);
        }
        
        public System.Threading.Tasks.Task<string> GetStationAsync(string key) {
            return base.Channel.GetStationAsync(key);
        }
    }
}
